### ISSUE TITLE
APKMT Alpha2 decompile systemui.apk for 4.0.2

### ISSUE THREAD

**Issue by nastiestceo** [broo2s/brut.apktool#10]
When i use the apk multi tool to decompile the 4.0.2 systemui.apk it error's out after "test" and when i look into my project folder i am left with only smali here is the log from the error

java version "1.7.0"

Java(TM) SE Runtime Environment (build 1.7.0-b147)

Java HotSpot(TM) 64-Bit Server VM (build 21.0-b17, mixed mode)

Could Not Find C:\Users\mikeyinid\Desktop\GS2\Apk_Manager_5.0.2\place-apk-here-for-modding../place-apk-here-for-modding/signedSystemUI.apk

Could Not Find C:\Users\mikeyinid\Desktop\GS2\Apk_Manager_5.0.2\place-apk-here-for-modding../place-apk-here-for-modding/unsignedSystemUI.apk

I: Baksmaling...

I: Loading resource table...

Exception in thread "main" brut.androlib.AndrolibException: Multiple resources: spec=0x7f0a000e dimen/status_bar_icon_drawing_size, config=-v13

```
    at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:65)

    at brut.androlib.res.data.ResConfig.addResource(ResConfig.java:58)

    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:196)

    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:165)

    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:130)

    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:105)

    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:82)

    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:48)

    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:315)

    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:50)

    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:43)

    at brut.androlib.Androlib.getResTable(Androlib.java:44)

    at brut.androlib.ApkDecoder.getResTable(ApkDecoder.java:148)

    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:98)

    at brut.apktool.Main.cmdDecode(Main.java:120)

    at brut.apktool.Main.main(Main.java:57)
```

**Comment by Inaciomcr** [comment]
this happens to me too, but with 4.0.3 systemui.apk
