### ISSUE TITLE
Cant decompile ICS APKs

### ISSUE THREAD

**Issue by raziel23x** [broo2s/brut.apktool#7]
I: Baksmaling...
I: Loading resource table...
I: Decoding resources...
I: Loading resource table from file: C:\Users\Silver\apktool\framework\1.apk
W: Could not decode attr value, using undecoded value instead: ns=android, name=hardwareAccelerated, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=android, name=alpha, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=alpha, value=0x00000000
S: Could not decode file, replacing by FALSE value: mipmap-xhdpi/ic_launcher_settings.png
S: Could not decode file, replacing by FALSE value: mipmap-hdpi/ic_launcher_settings.png
S: Could not decode file, replacing by FALSE value: mipmap-mdpi/ic_launcher_settings.png
W: Could not decode attr value, using undecoded value instead: ns=android, name=valueFrom, value=0x00000000
W: Could not decode attr value, using undecoded value instead: ns=android, name=valueTo, value=0x3f800000
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 0x010300e9
    at brut.androlib.res.data.ResPackage.getResSpec(Unknown Source)
    at brut.androlib.res.data.ResTable.getResSpec(Unknown Source)
    at brut.androlib.res.data.ResTable.getResSpec(Unknown Source)
    at brut.androlib.res.data.value.ResReferenceValue.getReferent(Unknown Source)
    at brut.androlib.res.data.value.ResReferenceValue.toResXmlFormat(Unknown Source)
    at brut.androlib.res.data.value.ResStyleValue.serializeToXml(Unknown Source)
    at brut.androlib.res.AndrolibResources.generateValuesFile(Unknown Source)
    at brut.androlib.res.AndrolibResources.decode(Unknown Source)
    at brut.androlib.Androlib.decodeResourcesFull(Unknown Source)
    at brut.androlib.ApkDecoder.decode(Unknown Source)
    at brut.apktool.Main.cmdDecode(Unknown Source)
    at brut.apktool.Main.main(Unknown Source)

**Comment by broo2s** [comment]
Fixed in v1.4.2
